// Serbo-Croatian (ijekavica), sentence case, plain verbs.
// Single source for every visible string. No component hardcodes copy.

export const sr = {
  turn: {
    you: "Ti si na potezu",
    other: (name: string) => `${name} je na potezu`,
    thinking: "Razmišlja",
    secondsLeft: (n: number) => `${n} s`,
  },
  table: {
    empty: "Sto je prazan",
    handEmpty: "Ruka prazna",
    jackClear: "Žandar — kupi sve",
    rankMatch: "Isti rank",
    sumMatch: "Zbir",
    chooseCapture: "Izaberi koje karte kupiš",
    trailHint: "Tapni sto da spustiš kartu",
    blockedTitle: "Moraš kupiti karte",
    blockedBody: "Sa ovom kartom postoji kupovina, pa ne možeš ostaviti kartu na stolu. Izaberi jednu od označenih grupa.",
    pot: "Ulog",
  },
  deck: {
    remaining: "Karata u špilu",
  },
  hand: {
    selectHint: "Dodirni kartu da je podigneš",
  },
  seat: {
    score: "Poeni",
    coins: "Žetoni",
    cards: (n: number) => `${n} karata u ruci`,
  },
  connection: {
    connected: "Na vezi",
    reconnecting: "Ponovno povezivanje",
    abandoned: "Napustio igru",
  },
  suits: {
    clubs: "Tref",
    diamonds: "Karo",
    hearts: "Srce",
    spades: "Pik",
  },
  reveal: {
    sweep: "ŽANDAR — počistio sto!",
    captures: (name: string) => `${name} kupi`,
    trails: (name: string) => `${name} spušta`,
    autoPlay: "automatski potez",
    playedLabel: "Odigrana karta",
    takenLabel: "Kupljene karte",
  },
  score: {
    title: "Rezultat",
    target: (n: number) => `do ${n}`,
    teamA: "Tim A",
    teamB: "Tim B",
    expand: "Prikaži razradu",
    collapse: "Sakrij razradu",
    hand: (n: number) => `${n}. dijeljenje`,
    noHands: "Nema odigranih dijeljenja",
    mostCards: "Najviše karata",
    mostClubs: "Najviše trefova",
    twoOfClubs: "2 tref",
    tenOfDiamonds: "10 karo",
  },
  reactions: {
    title: "Reakcije",
    labels: {
      laugh: "Smijeh",
      wow: "Ma nemoj",
      fire: "Vatra",
      clap: "Bravo",
      cry: "Suze",
      angry: "Ljutnja",
      thinking: "Razmišljam",
      respect: "Svaka čast",
    },
  },
  end: {
    handTitle: (n: number) => `Ruka #${n} gotova`,
    handPoints: "Poeni iz ove ruke:",
    matchTotal: "Ukupni rezultat:",
    matchWinner: (name: string) => `${name} pobjeđuje!`,
    nextHand: "Sljedeća ruka →",
    waitingHand: "Čeka se da host pokrene sljedeću ruku…",
    rematch: "Revanš (isti sto)",
    waitingRematch: "Čeka se da host pokrene revanš…",
    newTable: "Novi sto i igrači",
    leave: "Izađi na početnu",
    closeLabel: "Zatvori i idi na početnu",
    pending: "...",
  },
  pause: {
    waitingFor: (name: string) => `${name} se ponovo povezuje`,
    unknownPlayer: "Igrač",
    body: "Igra je pauzirana dok se igrač ne vrati. Sačekaj ili pokreni glasanje o prekidu.",
    seconds: (n: number) => `${n} s`,
    keepWaiting: "Sačekaj još",
    voteTitle: "Glasanje o prekidu",
    voteBody: "Igrač se ne vraća. Odluči hoćeš li čekati dalje ili prekinuti partiju.",
    voteWait: "Čekaj",
    voteEnd: "Prekini",
    voteNone: "Nije glasao",
    abandonedTitle: "Partija je prekinuta",
    abandonedBody: "Partija je završena jer je igrač napustio igru. Možeš izaći i započeti novu.",
    leave: "Izađi",
  },
} as const;
